module.exports = Object.freeze([
  
  {
    country: "England",
    flag: "en.12159c6.png",
    league: "Premier League",
    logo: "YXNYEC9j-OrdQOnn4.png",
    num: "198",
    top: true,
    season: "172",
    year: 2021,
    id: "dYlOSQOD",
    standingsId: "tdkpynmB_6kJqdMr2",
    standings: "on",    
    title: "ENGLAND: Premier League¬",
  },
  {
    country: "England",
    flag: "en.12159c6.png",
    league: "Championship",
    logo: "6a9KSp97-IRpaW1Pn.png",
    num: "198",
    top: false,
    season: "172",
    year: 2021,
    id: "2DSCa5fE",
    standingsId: "2BwgZPHN_4AK0LPz9",
    standings: "on",    
    title: "ENGLAND: Championship¬",
  },
  {
    country: "England",
    flag: "en.12159c6.png",
    league: "League One",
    logo: "j9pdDSV1-x68Bg5KH.png",
    num: "198",
    top: false,
    season: "172",
    year: 2021,
    id: "rJSMG3H0",
    standingsId: "bVIEi5HA_AHdHU0cr",
    standings: "on",    
    title: "ENGLAND: League One¬",
  },
  {
    country: "England",
    flag: "en.12159c6.png",
    league: "League Two",
    logo: "OWHCHi8j-Gd7FhPZN.png",
    num: "198",
    top: false,
    season: "172",
    year: 2021,
    id: "0MwU4NW6",
    standingsId: "tWVgqvO2_IXpllt4K",
    standings: "on",    
    title: "ENGLAND: League Two¬",
  },

  {
    country: "Germany",
    flag: "de.494bda8.png",
    league: "Bundesliga",
    logo: "bgn7cVkD-YRGF4M2N.png",
    num: "81",
    top: true,
    season: "172",
    year: 2021,
    id: "W6BOzpK2",
    standingsId: "UJfO5MeL_jFKYts6j",
    standings: "on",    
    title: "GERMANY: Bundesliga¬",
  },
  {
    country: "Germany",
    flag: "de.494bda8.png",
    league: "2. Bundesliga",
    logo: "vce9YRA7-rN7pvd6A.png",
    num: "81",
    top: false,
    season: "172",
    year: 2021,
    id: "tKH71vSe",
    standingsId: "OtfS4tBR_8zXO5Qri",
    standings: "on",    
    title: "GERMANY: 2. Bundesliga¬",
  },
  {
    country: "Spain",
    flag: "es.ac54d02.png",
    league: "LaLiga",
    logo: "CEyhlKT1-xdZKxEGc.png",
    num: "176",
    top: true,
    season: "172",
    year: 2021,
    id: "QVmLl54o",
    standingsId: "Ghz5Q5lg_MPV5cuep",
    standings: "on",  
    title: "SPAIN: LaLiga¬",
  },
  {
    country: "Spain",
    flag: "es.ac54d02.png",
    league: "LaLiga2",
    logo: "l8Md7EhU-CAPqRuT5.png",
    num: "176",
    top: false,
    season: "172",
    year: 2021,
    id: "vZiPmPJi",
    standingsId: "COPVQP3a_0GU9daAj",
    standings: "on",  
    title: "SPAIN: LaLiga2¬",
  },
  {
    country: "Italy",
    flag: "it.225fa57.png",
    league: "Serie A",
    logo: "nNGpajA7-h6SSPSBT.png",
    num: "98",
    top: true,
    season: "172",
    year: 2021,
    id: "COuk57Ci",
    standingsId: "U13F0eui_YHxmuFsJ",
    standings: "on",    
    title: "ITALY: Serie A¬",
  },
  {
    country: "Italy",
    flag: "it.225fa57.png",
    league: "Serie B",
    logo: "8rfDEpSp-vggIoxKj.png",
    num: "98",
    top: false,
    season: "172",
    year: 2021,
    id: "6oug4RRc",
    standingsId: "8h2JaFfc_jwkw4bKJ",
    standings: "on",    
    title: "ITALY: Serie B¬",
  },
  {
    country: "France",
    flag: "fr.f5e7288.png",
    league: "Ligue 1",
    logo: "QmK6Kf97-6NgdhIvA.png",
    num: "77",
    top: true,
    season: "172",
    year: 2021,
    id: "KIShoMk3",
    standingsId: "GfTM50Dt_0W4LIGb1",
    standings: "on",    
    title: "FRANCE: Ligue 1¬",
  },
  {
    country: "France",
    flag: "fr.f5e7288.png",
    league: "Ligue 2",
    logo: "vPattcCO-4dAZ4vHn.png",
    num: "77",
    top: false,
    season: "172",
    year: 2021,
    id: "Y35Jer59",
    standingsId: "l8RU3vrg_hfwSuv6E",
    standings: "on",    
    title: "FRANCE: Ligue 2¬",
  },
  {
    country: "Austria",
    flag: "at.693357d.png",
    league: "Admiral Bundesliga",
    logo: "W05KfZ8j-MNJgo8mj.png",
    num: "25",
    top: false,
    season: "172",
    year: 2021,
    id: "rJg7S7Me",
    standingsId: "QRXf5u07_nXhNbiaL",
    standings: "on",    
    title: "AUSTRIA: Admiral Bundesliga¬",
  },
  {
    country: "Belgium",
    flag: "be.35385b1.png",
    league: "Jupiler League",
    logo: "YDHHaKRp-CY1uDaWT.png",
    num: "32",
    top: false,
    season: "172",
    year: 2021,
    id: "dG2SqPrf",
    standingsId: "A5OjIAzd_88GNJ4I9",
    standings: "on",    
    title: "BELGIUM: Jupiler League¬",
  },
  {
    country: "Netherlands",
    flag: "nl.dede5ef.png",
    league: "Eredivisie",
    logo: "SpYO5tjD-hnSMvjTH.png",
    num: "139",
    top: false,
    season: "172",
    year: 2021,
    id: "Or1bBrWD",
    standingsId: "foAgEPBk_SfQjVhXC",
    standings: "on",  
    title: "NETHERLANDS: Eredivisie¬",
  },
  {
    country: "Portugal",
    flag: "pt.0e255ff.png",
    league: "Liga Portugal",
    logo: "ltrk8v9j-ddn4Dzs6.png",
    num: "155",
    top: false,
    season: "172",
    year: 2021,
    id: "UmMRoGzp",
    standingsId: "8lUak13D_SYQdiOke",
    standings: "on",    
    title: "PORTUGAL: Liga Portugal¬",
  },
  {
    country: "Russia",
    flag: "ru.362b4e4.png",
    league: "Premier League",
    logo: "ObQgZxhU-AqGlVXiO.png",
    num: "158",
    top: false,
    season: "172",
    year: 2021,
    id: "YacqHHdS",
    standingsId: "I1pdAHVM_rBGSvxB4",
    standings: "on",    
    title: "RUSSIA: Premier League¬",
  },
  {
    country: "Ukraine",
    flag: "ua.cbd8dc2.png",
    league: "Premier League",
    logo: "EeTnTP9j-M9UJzeRi.png",
    num: "195",
    top: false,
    season: "172",
    year: 2021,
    id: "Myjs3vp6",
    standingsId: "noC6OeQ1_I1A4Gzb5",
    standings: "on",    
    title: "UKRAINE: Premier League¬",
  },
  {
    country: "Turkey",
    flag: "tr.2e7ac0b.png",
    league: "Super Lig",
    logo: "zXKzgj7j-GIYgD8MG.png",
    num: "191",
    top: false,
    season: "172",
    year: 2021,
    id: "Opdcd08Q",
    standingsId: "8KAQ0plf_zLsIuMTj",
    standings: "on",  
    title: "TURKEY: Super Lig¬",
  },  
  {
    country: "Scotland",
    flag: "sc.c794ec4.png",
    league: "Premiership",
    logo: "bDvLJ79j-tMLGFoII.png",
    num: "199",
    top: false,
    season: "172",
    year: 2021,
    id: "tGwiyvJ1",
    standingsId: "v7anOtOT_GMqQMiu6",
    standings: "on",
    title: "SCOTLAND: Premiership¬",
  },   
    
  {
    region: "Europe",
    country: "Europe",
    flag: "world.ee5f190.png",
    league: "Champions League",
    logo: "O6Uk9m8j-ETtnrNtN.png",
    num: "6",
    top: false,
    season: "172",
    year: 2021,
    id: "xGrwqq16",
    standings: "off",
    title: "EUROPE: Champions League - Group Stage¬",
  },
  {
    region: "Europe",
    country: "Europe",
    flag: "world.ee5f190.png",
    league: "Europa League",
    logo: "Op7gjxUp-CERFEyO3.png",
    num: "6",
    top: false,
    season: "172",
    year: 2021,
    id: "ClDjv3V5",
    standings: "off",
    title: "EUROPE: Europa League - Group Stage¬",
  },
  {
    region: "Europe",
    country: "Europe",
    flag: "world.ee5f190.png",
    league: "Europa Conference League",
    logo: "hIGmsTXI-z92hbnY0.png",
    num: "6",
    top: false,
    season: "172",
    year: 2021,
    id: "GfRbsVWM",
    standings: "off",
    title: "EUROPE: Europa Conference League - Group Stage¬",
  },  
  {
    region: "Europe",
    country: "Europe",
    flag: "world.ee5f190.png",
    league: "World Cup",
    logo: "hjGIig9j-0EdkoDVL.png",
    num: "6",
    season: "156",
    year: 2021,
    id: "lvUBR5F8",
    standings: "off",
    title: "EUROPE: World Cup - Qualification¬",
  },
  {
    region: "Europe",
    country: "Europe",
    flag: "world.ee5f190.png",
    league: "UEFA Nations League",
    logo: "dKtyQxDO-rLdejT9t.png",
    num: "6",
    top: false,
    season: "172", 
    year: 2021,
    id: "A9yxE9Ke",
    standings: "off",
    title: "EUROPE: UEFA Nations League - League A - Play Offs¬",
  },  
  
]);
