

### login
POST http://localhost:4001/login
Content-Type: application/json

{ "email" : "admin@gmail.com", "password" : "qwerty" }

### signup
POST http://localhost:4001/signup
Content-Type: application/json

{ "name" : "admin2",  "email" : "admin2@gmail.com",  "password" : "qwerty" }


###
GET http://localhost:4001/api/v1/standings/demo
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGNmNmU0NzM5NDMyMTczMDdlYTc2OSIsImlhdCI6MTY1NTc0NDI0OSwiZXhwIjoxNjU4MzM2MjQ5fQ.NsaVT0jCayKWDEOrmM0vD-gtwFXdnPQni-ogYAumqAU


###
GET http://localhost:4001/api/v1/standings/england/dYlOSQOD/demo